system:
    apiPrefix: /api
    debug: true
    init: true
web:
    db:
        type: sqlite
        path: ./data/go-ai-agent.db
    server:
        port: 19009
flow:
    cache:
        enabled: true
        path: ./data/cache
    maxConcurrency: 4
